//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using Domain.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ComercializadoraDbEntities1 : DbContext
    {
        public ComercializadoraDbEntities1()
            : base("name=ComercializadoraDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Products> Products { get; set; }
    
        public virtual int sp_CreateMassiveProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CreateMassiveProducts");
        }
    
        public virtual int sp_DeleteAllProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteAllProducts");
        }
    }
}
